# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testCocoapods_swift4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AceAnalytics'

  # Pods for testCocoapods_swift4

  target 'testCocoapods_swift4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testCocoapods_swift4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
